### ISSUE TITLE
Add credentials provider to provide credential encryption and remove plaintext passwords and keys from accompli.json

### ISSUE THREAD

**Issue by niels-nijens** [accompli/accompli#11]
Accompli currently implements the possibility to retrieve credentials for SSH from external sources. Yet,  when for example an FTP adapter is implemented (or when using SSH with password) you still need to provide passwords in your accompli.json.

This method is unsafe as it potentially expose credentials to outsiders.

Accompli should be able facilitate tooling to encrypt credentials stored in the accompli.json file in a way possibly similar to encryption methods used by [Travis CI](http://docs.travis-ci.com/user/encryption-keys/).
### Todo
- [ ] Create a credentials provider.
- [ ] Implementation for supplying a decryption key with current commands.
- [ ] (Optional) Provide a command to generate a private key which is directly stored within the credentials storage.
- [ ] (Optional) Provide a command to generate a unique key (see #171).

**Comment by RonRademaker** [comment]
Brainstorming a bit here, some ideas in arbitrary orde:

- credentials storage (something like jenkins uses)
- ssh keys
- you might need to set up a non-interactive deployment (i.e. say deploy to production at midnight), do this interactive and ask for credentials. This could result in a (scheduled) command that has the credentials as local variables so they're destroyed after usage.
- configure it in a local parameter file, like you would database credentials in any web app
- maybe SSO solutions like oauth (Jaap is looking at this right now) can work

**Comment by RonRademaker** [comment]
I created a CredentialsProvider library a while ago (docs are on our confluence) that'll allow you to inject credentials somewhere, maybe this could also be useful?

**Comment by niels-nijens** [comment]
I don't think it's very useful to publicly share information about proprietary software to a not directly to Connect Holland related opensource project.

This issue was actually intended to be merely a reminder for a (required) feature for now. That's why I haven't added a description stating a clear purpose and scenario. I will add this soon.

**Comment by RonRademaker** [comment]
A simpler solution for this could be to allow loading credentials, like an ssh key or oauth token, from a file that's not part of your repository. Something like `~/.ssh/my-private.key` for example.
