### ISSUE TITLE
Extend documentation

### ISSUE THREAD

**Issue by niels-nijens** [accompli/accompli#73]
To improve usability of Accompli extensive documentation needs to be added.
### To-do
- [x] Introduction / explanation of concepts
- [x] Installation
- [x] Getting started
- [x] Accompli.json configuration
  - [x] Reference
  - [x] Extending from other configurations
- [x] Tasks
  - [x] Introduction
  - [x] List of tasks categorized by install and deploy
  - [x] Detailed descriptions of each task (with listening events highlighted in the event flow schema)
    - [x] CreateWorkspaceTask
    - [x] DeployReleaseTask
    - [x] MaintenanceModeTask
    - [x] RepositoryCheckoutTask
  - [x] How to create your own task
- [x] Connection adapters
- [ ] ~~Deployment strategies~~

The created markdown pages can later on be rendered as webpages.

Related issues: #14 #15
